[package]
name = "prost-compiler"
description = "prost-compiler."
version = "0.0.0"
authors = ["Andrew Hickman <andrew.hickman1@sky.com>"]
repository = "https://github.com/andrewhickman/prost-compiler"
documentation = "https://docs.rs/prost-compiler"
license = "MIT OR Apache-2.0"
readme = "README.md"
edition = "2018"

[dependencies]
logos = "0.12.0"
miette = "4.7.1"
prost-types = "0.10.1"
thiserror = "1.0.31"

[dev-dependencies]
